name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r church_project/requirements.txt
    - name: Run Tests
      working-directory: church_project
      env:
        SECRET_KEY: 'test-secret-key-12345'
        CI: true
        DJANGO_SETTINGS_MODULE: church_site.settings
        AWS_ACCESS_KEY_ID: "mock_access_key"
        AWS_SECRET_ACCESS_KEY: "mock_secret_key"
        AWS_STORAGE_BUCKET_NAME: "mock-bucket"
        AWS_S3_ENDPOINT_URL: "https://mock.endpoint"
        ACCOUNT_ID: "mock_account_id"
        CSRF_TRUSTED_ORIGINS: "http://localhost"
        STATIC_URL: "/static/"
        EMAIL_HOST_PASSWORD: "mockpassword"
        EMAIL_HOST_USER: "mock@email.com"
        VAPID_PUBLIC_KEY: "mock_public_key"
        VAPID_PRIVATE_KEY: "mock_private_key"
        VAPID_ADMIN_EMAIL: "mock@email.com"
      run: |
        python manage.py test
